### ISSUE TITLE
Wrong 'disabled' background color for themes other than default dark

### ISSUE THREAD

**Issue by righthandprincess** [EpicGamesExt/raddebugger#109]
The disabled background color for items in panels, such as the call stack or the watch window, appear to be for the default dark theme, and not whichever theme you currently have selected.

This happens when actively debugging an application, and the debugger is not paused.
![raddbg_aShasH7LRW](https://github.com/EpicGames/raddebugger/assets/145483897/fcd6009e-3ab0-4c30-8391-d84a239a689f)

**Comment by ryanfleury** [comment]
Thanks for the fix! Closing this issue now.
