### ISSUE TITLE
Feature: Debugger stepping time

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#129]
I was going through the blog about Rider 2024.1 EAP3 changes and found this feature interesting, haven't used it though so not sure if it will be as helpful as it sounds. What do you think?

![Screenshot 2024-02-02 212954](https://github.com/EpicGames/raddebugger/assets/29519295/81e77c43-c3c5-4904-968b-f13142adcfeb)

**Comment by jeffrbig2** [comment]
I think we'll have some proper profiling stuff for this eventually. Macro timing this stuff with debugger roundtripping is misleading most of the time.  I guess we could show if if the time was greater than 100ms or something.  But yeah, I'd prefer to handle this in a more real way.
