### ISSUE TITLE
Invisible scroll bars with VS Light theme

### ISSUE THREAD

**Issue by tom-seddon** [EpicGamesExt/raddebugger#147]
The thumb and bar are the same colour.

![image](https://github.com/EpicGames/raddebugger/assets/1269020/a068ae74-a761-4ecf-884c-99f7476c7598)

**Comment by tom-seddon** [comment]
The contrast isn't that significant for the dark themes either, but it is possible to tell which bit is which.

**Comment by ryanfleury** [comment]
This should be better in the default theme presets as of 0.9.11. There is also now a completely separate theme color slot for scroll bar buttons, which should make it easy to customize them to be more visible to one's liking.
