### ISSUE TITLE
No feedback from integer divide by zero

### ISSUE THREAD

**Issue by bryantdrewjones** [EpicGamesExt/raddebugger#151]
I had some code that was accidentally doing a divide by zero. It basically looked like this:

```c
volatile unsigned zero = 0; // `volatile` so the compiler doesn't notice the divide by 0
unsigned bad_value = (zero % zero); // <-- debugger stalls with no feedback here
```

It took me a few extra moments to track down because I wasn't getting any feedback from the debugger. It showed my app in a green running state, even though execution stopped on the line that threw the exception. Should the debugger go into its red-coloured error state in this case? Is it possible to output an error message about the exception?

(This may be the same request as #120--not sure!).

**Comment by Lperlind** [comment]
I hit this too. Was easy to track down by just looking at the callstack, but some feedback from the debugger would be appreciated.

**Comment by mmozeiko** [comment]
It looks like a bug in debugger, it should not hang like that.

But if you enable "0xc0000094 Division by Zero" exception in View -> Exception Filters, then debugger correctly stops on exception.
