### ISSUE TITLE
Ctrl+Insert/Shift+Insert for copy/paste

### ISSUE THREAD

**Issue by sndels** [EpicGamesExt/raddebugger#156]
These would be nice to have in addition to ctrl+c/ctrl+v as they can be a bit more universal across different environments.

**Comment by ryanfleury** [comment]
These bindings will automatically be registered upon first-time startup as of ac9a9084641afa70c1c5869ec6e7f88491df8eab. To get them in your local copy, you'll either want to add them manually to your user file (located in `%appdata%/raddbg/default.raddbg_user` by default), or (less preferably) delete your user file. The UI doesn't currently support editing multiple bindings per command, but I've made note to add this.
