### ISSUE TITLE
raddbg --ipc commands only execute upon window event

### ISSUE THREAD

**Issue by MaliusArth** [EpicGamesExt/raddebugger#157]
raddbg --ipc commands are not executed right away, instead, they are executed once you hover over the rad debugger window or the window gets focused.

I'm not sure if this is the expected behavior, but it makes sense to allow IPCs to choose whether or not to wait for window events to be processed.

**Comment by ryanfleury** [comment]
Fixed as of f431ac7f80a042dfc611c30e5e50e52803f6e44f.
