### ISSUE TITLE
F5 between 2 continuous breakpoints shows the wrong value in the watch window

### ISSUE THREAD

**Issue by longtran2904** [EpicGamesExt/raddebugger#166]
F5 between 2 continuous breakpoints behaves differently from F10. In this video, when I started debugging, the code will always init the `logThread.arena`, making its position 64. When I first debug the code with F5, the result in the watch window is 0, while when I use F10 later, you can see the result is 64.

https://github.com/EpicGames/raddebugger/assets/53656110/9b606fd8-0b7b-4c69-ba0b-7ec7de165ac2

**Comment by mmozeiko** [comment]
I can reproduce this problem with following code:
```
__declspec(thread) int x;

int main()
{
	x = 42;
	x++;
	x++;
	x++;
	x++;
	return 0;
}
```
Compiled with `cl -Zi test.c`.
Putting breakpoint on all lines with `x++`, then running program shows x=0 regardless of using F5 or F10 when stopped on first x++. Pressing F10 again (so 3rd time) makes x value appear. Pressing F5 three times also makes x value to appear. So regardless of F5 or F10, x value appears when debugger stops 3 times.

Also putting `&x` in watch window shows very strange address. Something like `0x104` - which is not a valid pointer.

Another probably unrelated problem is that I cannot put breakpoint on x=42 line. It just skips to x++.

**Comment by ryanfleury** [comment]
This eval/caching bug should be fixed now in `dev`, and this will be fixed in the next release. Let me know if you run into more issues with that. Investigating the weird breakpoint issue shown by Martins now...

**Comment by ryanfleury** [comment]
Fixed breakpoint issue as well. This was happening when a user breakpoint resolution was exactly matching the address of an entry point.
