### ISSUE TITLE
Wrong Disassembly view with AVX vmovdqu instruction

### ISSUE THREAD

**Issue by kiroxas** [EpicGamesExt/raddebugger#169]
I have invalid disassembly output for an AVX instruction.
Here what it looks like in Rad Debugger :

![rad_AVX](https://github.com/EpicGames/raddebugger/assets/3176062/f0d6777b-bb17-4103-888b-eea034f1a287)

And here the output in Visual Studio Code :  

![vs_AVX](https://github.com/EpicGames/raddebugger/assets/3176062/7fef8d22-744d-47b2-9da1-157736a3e6cf)

Seems like the library you're using for disassembly ( https://github.com/vmt/udis86 if I'm not mistaken )  
is failing on a vmovdqu instruction (this one  : [VEX.128.F3.0F.WIG 7F /r VMOVDQU xmm2/m128, xmm1](https://www.felixcloutier.com/x86/movdqu:vmovdqu8:vmovdqu16:vmovdqu32:vmovdqu64 )) reporting  wrong instruction and number of bytes read, which cascades in wrong next instructions display.

Quickly looking at the library, seems like there is no AVX-512 support either.

**Comment by ratchetfreak** [comment]
one option to fix this would be to switch to [intel's xed library](https://github.com/intelxed/xed/), 

Upside is that it's gonna be updated every time a new extension comes out, 

Down side is documentation is rather lacking, it uses a python build system (solvable) and a python generator to convert the data files into lookup tables (harder). Though you should be able to embed just the minimal sources + generated sources needed for decode into this repo if I understand the Apache license correctly.

**Comment by ryanfleury** [comment]
Fixed as of ccf8504dd1209503905dfb97a0210f2a20e2acaa. Let me know if you run into any other issues with this.
