### ISSUE TITLE
Pointer comparison in metagen

### ISSUE THREAD

**Issue by ramenguy99** [EpicGamesExt/raddebugger#171]
Hi,

I run into an issue while running metagen on Linux. I don't fully understand the purpose of these pointer comparisons (`it < opl`) here:

https://github.com/EpicGamesExt/raddebugger/blob/c757388bb409e8670b63e31033e0ea0658587484/src/metagen/metagen.c#L363

and here:

https://github.com/EpicGamesExt/raddebugger/blob/c757388bb409e8670b63e31033e0ea0658587484/src/metagen/metagen.c#L422

It looks like when running metagen the value of `opl` is always a pointer to `md_nil_node`, on windows the global is usually mapped at a large address, making the comparison always a no-op, while on linux it's always failing due to being mapped at a much lower address than where other nodes end up being allocated, causing the program to segfault / produce wrong output.

Changing the check to `!=` instead of `<` seems to fix the issue, but I'm not sure why they were there in the first place.

**Comment by ryanfleury** [comment]
Yep, dumb mistake. `!=` is indeed the correct version. Fixed now on `demon2`, where I am doing a bunch of major work, and once I finally merge back into `dev` and then into `master`, it'll be in the next release.
