### ISSUE TITLE
Digit separator messes up C++ highlighting

### ISSUE THREAD

**Issue by yudi-azvd** [EpicGamesExt/raddebugger#173]
## RAD Debugger v0.9.8-alpha

It's not critical or anything, but the following snippet

    sound_output.samples_per_second   = 48'000;

at line 429 (see image below) causes everything after to render in yellow.

![image](https://github.com/EpicGamesExt/raddebugger/assets/37981839/08f6610c-3c5f-4003-9397-034d2984a8c8)

Maybe the character `'` starts a string sequence or something.

**Comment by ryanfleury** [comment]
Fixed in ca6e75d46616748b2d7ec9930d3887e11d0e2180. This will be in the next release.
