### ISSUE TITLE
Call stack & registers are not shown when rsp is changed

### ISSUE THREAD

**Issue by DeadBlasoul** [EpicGamesExt/raddebugger#175]
I was debugging my own implementation of fibers on Windows, when suddenly I noticed, that changing rsp to a new area breaks call stack & registers shown in the debugger. The problem is present until I change rsp back to original thread's stack.

This behavior is also present when using WinAPI fibers, so to reproduce it you can just create a fiber and immediately switch to it.

Breakpoints are working, but the arrow is missing. You can see it on the screenshot.

![image](https://github.com/EpicGamesExt/raddebugger/assets/29898954/02e18059-12aa-41a7-99ed-8a190d8dc019)

**Comment by ryanfleury** [comment]
I believe this has been addressed by my recent passes over the process control layers. I now get correct behavior when testing with Win32 fibers:

![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/0465d3d3-c630-4e45-b504-a913385b7802)

You can test these new changes on the `dev` branch. Please let me know if these passes did not address this issue, and if you're still experiencing it.
