### ISSUE TITLE
Cannot see source code to add breakpoints [gcc]

### ISSUE THREAD

**Issue by dacanizares** [EpicGamesExt/raddebugger#177]
Hi,

I have a simple C program that I'm compiling with gcc. It generates the **.pdb** file but when I open the executable with raddebugger I cannot see the source code to add breakpoints. **It generates a raddbg file** but the debugger just shows a disassembled code when I run it. Am I doing something wrong?

```c
#include <stdio.h>

int main(int argc, char *args[])
{
    int n = 1;
    printf("%d", n);
    return 0;
}
```

I'm using this command to compile:

```
gcc main.c -g -ggdb -gcodeview
```

Thanks.

**Comment by mmozeiko** [comment]
As far as I know codeview support in gcc is in very early stage. It is pretty incomplete. I tried it last year and if I remember correctly they only had line number info, no local symbols/types, and sometimes pdb file was not loading properly in Visual Studio at all for me. Not sure how much it has changed now. I think they plan to officially release it in gcc 14, but no idea about how complete it will be.

It should be no problem to support what gcc generates, but they should first implement more complete pdb generation, it does not make much sense to spend resources on this in debugger at this moment. At least until they'll include support for codeview output in official release.

**Comment by dacanizares** [comment]
Thanks!
