### ISSUE TITLE
[enhancement] - Better scrolling when using the trackpad

### ISSUE THREAD

**Issue by DeliciousLines** [EpicGamesExt/raddebugger#178]
When using the trackpad, scrolling does not happen unless I really swipe a lot. I could not find a way to disable smooth scrolling in the current version of the debugger (0.9.8 alpha), so I do not know how scrolling from the trackpad would behave without that.

**Comment by ryanfleury** [comment]
This should work better after d560f8c734ba87fd1ea79e2dd5fefb6e3031fe00.

**Comment by DeliciousLines** [comment]
This is way better, thank you!
