### ISSUE TITLE
Wide strings only show the first character in the Watch window

### ISSUE THREAD

**Issue by zobermiller** [EpicGamesExt/raddebugger#180]
I have the following code snippet:

```
#include <stdio.h>

int main()
{
    char* string1 = "This is a narrow string.\n";
    wchar_t* string2 = L"This is a wide string.\n";

    return 0;
}
```

Compiled with

```
cl /Zi /Od main.c
```

`string1` shows the entire string contents in the Watch window, but `string2` only shows the first `"T"`:

![image](https://github.com/EpicGamesExt/raddebugger/assets/4643387/9dce232e-d83c-4a9b-8a6e-0d9ddf658973)

Changing the View Rule to "text" or something else doesn't have any effect, though using something like `array:20` will allow me to expand it to see all the characters in an array-like format.

I assume this is because technically speaking the second byte of the `"T"` character is a 0, so it thinks that's the end of the null-terminated string. But just a guess.

**Comment by ryanfleury** [comment]
Fixed in 4b3941c17fc00a9715c8208d4bcea5fc880dd101. This is in `dev` and will be in the next release. The `text` view rule is still not going to visualize these correctly yet, but that is still an actively under-development feature.
