### ISSUE TITLE
struct/class data members and `this` is not working v0.9.9

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#181]
Version: v0.9.9 ALPHA
struct/class data members resolve to "could not be found" in watch window, nothing on hover and `this` resolves to `<nil>`
![image](https://github.com/EpicGamesExt/raddebugger/assets/29519295/13eb5ae6-2c53-4e82-b340-74dd86ae1186)

**Comment by ryanfleury** [comment]
Should've known to test C++ stuff with the new converter. :)

Thanks for your patience. This is fixed in 693d20ec1a7d5147abe2e1ec64a6ef15caa4639e. I'll push a 0.9.9b build which has this fix also.

**Comment by ryanfleury** [comment]
Just an update, all of these fixes are in an updated v0.9.9 build [here](https://github.com/EpicGamesExt/raddebugger/releases/tag/v0.9.9-alpha).
