### ISSUE TITLE
static variables is not working v0.9.9

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#182]
static variables are not working (both in watch and on hover) with or without namespaces regardless of the breakpoint location.
![image](https://github.com/EpicGamesExt/raddebugger/assets/29519295/12c226f8-0182-4cc0-8a9b-a26854440e0c)

**Comment by ryanfleury** [comment]
Also fixed in 693d20ec1a7d5147abe2e1ec64a6ef15caa4639e. Will push a new build with this fix shortly.

**Comment by MohitSethi99** [comment]
Thanks for all the hard work.
I tried the build and static variables are only showing up for struct/class. It doesn't work for global static, static within namespace and static in Base/Derived configuration.
![image](https://github.com/EpicGamesExt/raddebugger/assets/29519295/6d0d9854-2f33-4abe-be99-afc7bb7ecd9b)

**Comment by ryanfleury** [comment]
Are you sure that these statics are being referenced in your example? If the symbols are stripped because they are not being used, they effectively don't exist to the debugger.

![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/c972bbad-f711-456f-a1a2-ecac75c72fd6)

**Comment by MohitSethi99** [comment]
Yeah you are right, I didn't knew symbols will be stripped in debug mode. It works fine, sorry for the negligence.
Btw nice take on c_plus_plus haha

**Comment by ryanfleury** [comment]
No problem, glad it's working! :)
