### ISSUE TITLE
Inherited and base members doesn't show up if class has virtual functions and base to derived class autocast not working. v0.9.9

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#183]
Version: 0.9.9 ALPHA
Last fix: d3931fd
![image](https://github.com/EpicGamesExt/raddebugger/assets/29519295/a9fc5985-eb20-4466-a4bd-8ddfcfdcad7f)

**Comment by ryanfleury** [comment]
Fixed in 7c0ce2ab54ef85fb7a35ae346b35f880eb6861a2. Along with the other fixes will push a new build with this fix included.
