### ISSUE TITLE
Cross-module type cast

### ISSUE THREAD

**Issue by GloriousPtr** [EpicGamesExt/raddebugger#185]
We use some upper bits in pointer to store data and pass it around as struct containing u64, we can mask the pointer with 0x0000FFFFFFFFFFFF and cast it to the appropriate type in watch window but it doesn't work with raddebugger if the type is not in the current module (where we hit the breakpoint)

**Comment by MohitSethi99** [comment]
Can bump this? It is the only issue that gets in the way for me and had to use VS for work most of the time.
As described above, can't cast to a type unless the instruction pointer is in the module that knows the type.

**Comment by ryanfleury** [comment]
This is now done on `dev` and will be in 0.9.12.
