### ISSUE TITLE
The debugger removes '\' from paths when saving a target

### ISSUE THREAD

**Issue by moizifty** [EpicGamesExt/raddebugger#188]
As mentioned in the title, saving a target, if the target command line contains paths such as:

> ..\somefile.txt

This gets turned into:

> ..somefile.txt

when the debugger is opened up again.

**Comment by ryanfleury** [comment]
I’d guess this is because of the debugger’s serialization string escaping rules—I’ll fix this, but in the meantime, using forward slashes might help. I can’t test at the moment but that should hopefully unblock anything.

**Comment by ryanfleury** [comment]
Fixed in d560f8c734ba87fd1ea79e2dd5fefb6e3031fe00.
