### ISSUE TITLE
Incomplete callstack

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#191]
Sometimes getting incomplete callstack, same behaviour in 0.9.8 as well.
Noticeable with setup involving calls between multiple dlls.

**Comment by MohitSethi99** [comment]
Not able to reproduce, but here's the screenshot of the same exception in raddebugger vs remedybg

![Rad](https://github.com/EpicGamesExt/raddebugger/assets/29519295/2d9c98b0-bb03-4003-b84f-cd498a8471a7)

![Remedybg](https://github.com/EpicGamesExt/raddebugger/assets/29519295/a500258b-be2c-417b-99f1-768a8174ab33)

**Comment by ryanfleury** [comment]
Fixed by #206.
