### ISSUE TITLE
Suggestion: UI commands displayed for mouse clicks

### ISSUE THREAD

**Issue by ChichiMsdk** [EpicGamesExt/raddebugger#194]
Hey, I think it would be cool to be able to step in, step out, finish, start etc .. Using the mouse and easily like in remedybg or visual studio. I don't know if it's already possible sorry if it is.
![raddbg](https://github.com/EpicGamesExt/raddebugger/assets/111235918/0731b28a-d95c-488e-a6fb-cabbe7253992)

**Comment by ryanfleury** [comment]
Done in 9f4aade2e1c7783a3695725bf2c05f716d10013e. This is available on `dev` and will be in the next release.
