### ISSUE TITLE
Error starting a process if "Working Directorty" starts with a whitespace

### ISSUE THREAD

**Issue by romasandu-gaijin** [EpicGamesExt/raddebugger#197]
Title basically says it all, whitespaces should be trimmed from target configuration fields. I.e. `D:/stuff/game/` works fine as the working directory, but ` D:/stuff/game/` (note the whitespace before the letter D) causes raddbg to fail to start a process without much explanation as to why.

**Comment by ryanfleury** [comment]
Fixed in 5d459d9b7afc55cd8db62f4e9a94b63aeb49d5e4.
