### ISSUE TITLE
Debugger doesn't seem to how values for HRESULT

### ISSUE THREAD

**Issue by moizifty** [EpicGamesExt/raddebugger#202]
Hi, 

Taking this example code:

```
#include <windows.h>

int main(void)
{
    HRESULT hr = 90;
}
```

Debugging this in raddebugger and trying to inspect the value for 'hr' does not work, it shows up as blank.

**Comment by ryanfleury** [comment]
Fixed in dc5dda3f718fb49cf6783ef2aef8069f45b015e0.
