### ISSUE TITLE
Access violation in dasm_parse_thread__entry_point

### ISSUE THREAD

**Issue by hkva** [EpicGamesExt/raddebugger#204]
I am consistently getting crashes when double-clicking call stack entries. It looks like `line->line_num` is 0 and is underflowing.

https://github.com/EpicGamesExt/raddebugger/blob/4aeb6d7d03ce65d385f5fad465501370400eee1b/src/dasm_cache/dasm_cache.c#L501

A fatal exception (code 0xc0000005) occurred. The process is terminating.

Call stack:
1. [0x7ff6481c2357] dasm_parse_thread__entry_point +3223, dasm_cache.c line 501
2. [0x7ff64819f3fa] w32_thread_base +90, os_core_win32.c line 173
3. [0x7ffc379e7344] KERNEL32
4. [0x7ffc38fc26b1] ntdll

Version: 0.9.9 [4aeb6d7]

**Comment by ryanfleury** [comment]
Fixed in f45ea18f24d62ab980f69d37f4707188e2f28169. This is new code for the intermixed disassembly view stuff so let me know if you run into more issues with this.
