### ISSUE TITLE
Breakpoints don't break anymore.

### ISSUE THREAD

**Issue by skejeton** [EpicGamesExt/raddebugger#225]
I've used previous version (0.9.9a) it was very nice, noticed the new version came out, and downloaded it, I see a lot of cool changes but the breakpoints don't work on the same project now, not sure why.

I downloaded the archive and extracted it to the same directory I put the previous version in (removing the old files). The executable has a PDB file alongside it, compiled with debug symbols, worked with the previous version, not sure what happened now.

**Comment by ryanfleury** [comment]
I'll need some more information to address this.

First, double click the breakpoint's location in the `Breakpoints` view:
![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/f7864c58-b287-4eb3-acbc-d6a9bcdf7ecc)

Then, right click the tab of the source view that is opened, and copy the full path:
![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/2a4b4bef-313b-4590-af10-430c3c42a06d)

Then, try stepping over the same location, without setting a breakpoint. Is it the same location, and is it the same file, or does it open in another tab?

Furthermore, a few other things you can look at:
- Is the debugger indicating that it has debug info in other ways? For instance, is it visualizing line info (via colors) in the source panel margin? Can you line-step? Is there source code information intermixed with disassembly?
- Delete all `.raddbg`, `.raddbgi`, `.rdi` files next to your project, and try again

If none of that provides any insight or works, then can you send me any of the following:
- A minimal repro EXE/PDB/RDI, for which breakpoints do not trigger
- Your `default.raddbg_user` and `default.raddbg_profile` files, located in `%appdata%/raddbg`
- The logs in `%appdata%/raddbg/logs`

**Comment by skejeton** [comment]
Yeah, it's indeed the same file; Colors disappeared too; Removing raddbg adjacent files in the bin directory didn't help.

However, removing the `bin` directory and rebuilding (cmake), did help. I have no idea what happened, but I'd guess it's not RAD Debugger's fault, I think this can be closed in this case.

**Comment by ryanfleury** [comment]
Hmmm, interesting. For one reason or another, it sounds like the debug info was busted, and not working. It should be fine to send here. I'll close this for now, but let me know if it happens again, and we can diagnose further.

**Comment by skejeton** [comment]
I've tested the program more, really good improvements, but this issue seems to re-occur, I can easily fix it with a re-build, so no big deal. If I try to debug with remedybg it works fine however, so I'm not sure what's the issue here. Here's the logs + user profile from that time:

[cfg.zip](https://github.com/EpicGamesExt/raddebugger/files/15451875/cfg.zip)

**Comment by ryanfleury** [comment]
Can you pull from master and build the debugger locally, and let me know if the same issue occurs? I fixed what I think is a related bug in #228.

**Comment by skejeton** [comment]
I checked, seems to work fine, if no problems occur in this couple of days I'll close this issue.

**Comment by MohitSethi99** [comment]
This happened to me thrice in a row just now. Had to delete all rdi files and rebuild the project to get it working.
Breakpoint was not getting hit all the time in the newly added code but was hitting 100% of the time in already existing code.
Also, it showed the coloured lines indicating debug info was available.

**Comment by skejeton** [comment]
Interesting, are you sure it wasn't using outdated debug info?

**Comment by MohitSethi99** [comment]
Maybe it's visual studio, I'll check again when I get back to work on Monday.

**Comment by MohitSethi99** [comment]
Here you go. It felt like it did hit the breakpoint and continued for some reason.

https://github.com/EpicGamesExt/raddebugger/assets/29519295/cfd63b0d-b54c-4caf-afb5-7f378998cdb8

**Comment by MohitSethi99** [comment]
Looks like there are some queued events that were not processed which are later processed when we hit a breakpoint.

**Comment by MohitSethi99** [comment]
Seems to be working fine now.
