### ISSUE TITLE
DEL should delete breakpoints in the breakpoints window

### ISSUE THREAD

**Issue by cmuratori** [EpicGamesExt/raddebugger#235]
Currently, there does not seem to be a way to delete breakpoints from the breakpoint window using the keyboard. You have to move the mouse to the trash icon and click it. It would be nice if DEL did that operation, similar to how it behaves in the watch window.

\- Casey

**Comment by ryanfleury** [comment]
This is now done on `dev` (as the Breakpoints UI is now just a special-case Watch UI), so this will be in 0.9.12. I don't recommend pulling & building from `dev` for now, since there are still a few broken things I am fixing up before release, but this'll be in an "official" build very shortly.
