### ISSUE TITLE
Clicking on a target should activate it, not edit it

### ISSUE THREAD

**Issue by cmuratori** [EpicGamesExt/raddebugger#237]
Editing a target is a fairly infrequent operation compared to setting it as the active target. It would be nice if the default operation for clicking on a target was to enable it, rather than having to move the mouse specifically to the small checkbox area next to the target. Editing a target could be an operation that it accessed from the right-click menu.

In combination with this change, it could be made so that clicking on the target selects that target _and only that target_, whereas clicking on the checkbox _adds_ the target, thereby making it slightly more intuitive to enable multiple targets.

\- Casey

**Comment by ryanfleury** [comment]
Made this change in: 62fa397e299175fef97251c34075f6cef363b154
