### ISSUE TITLE
View rule help box clips off the screen

### ISSUE THREAD

**Issue by cmuratori** [EpicGamesExt/raddebugger#238]
Currently, if the watch window is on the right side of the screen, hovering over the question-mark icon to show the view rule hover-help results in a window that is mostly off-screen and cannot be read. It would be nice if there was a default mechanism for ensuring hover-help always stays within the window so it can be read.

\- Casey

**Comment by ryanfleury** [comment]
Fixed: f808e8ae2987158ae1404b66251a34ac506c4b52
