### ISSUE TITLE
Crash report (unclear what provoked it)

### ISSUE THREAD

**Issue by cmuratori** [EpicGamesExt/raddebugger#243]
A fatal exception (code 0xc0000005) occurred. The process is terminating.
Call stack:
1. [0x7ff694ce7a5e] arena_release +14, base_arena.c line 89
2. [0x7ff694dee404] df_core_end_frame +1508, df_core.c line 8866
3. [0x7ff694eb4f26] update_and_render +4870, raddbg.c line 360
4. [0x7ff694cfc7ee] entry_point +6094, raddbg_main.cpp line 395
5. [0x7ff694cf6dbb] main_thread_base_entry_point +491, base_entry_point.c line 84
6. [0x7ff694eb76e0] w32_entry_point_caller +512, os_core_win32.c line 1801
7. [0x7ff694ce67f6] wWinMain +54, os_core_win32.c line 1813
8. [0x7ff694ed6ca2] __scrt_common_main_seh +262, exe_common.inl line 288
9. [0x7ffcd2577614] KERNEL32
10. [0x7ffcd29e26a1] ntdll
Version: 0.9.10

\- Casey

**Comment by ryanfleury** [comment]
Hm, it looks like this was in the recently-added unwind cache code, which had a silly mistake:
```
DLLPushBack(slot->first, slot->last, node); // (inserts into `slot` linked list)
MemoryZeroStruct(node); // (zeroes node, immediately destroying work done in previous step)
```
I can't prove this caused the bug just from the callstack, but this is a relatively simple cache and it's likely that this bug would lead to something like this, so I will mark this as "fixed" with the change I just pushed in 5778e75d663be3e329615febcc17179d1295ef7d. But don't hesitate to let me know if you see it again, after updating.
