### ISSUE TITLE
Text sometimes not copied into clipboard buffer when trying to copy something via Ctrl-C in the Watch View.

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#247]
A strange bug occurs when handling copy text (ctrl-C) via the keyboard in the Watch View. 

Step to reproduce:
1. Firstly, outside of the raddbg program copy any string into the clipboard buffer (ctrl-C) e,g, "xxxx".
2. Then inside raddbg input the text "foobar" into the first column of the Watch View.
3. The try selecting (right to left) the "foobar" text with your mouse but make sure the the mouse ends up outside of the Watch View.
![image](https://github.com/EpicGamesExt/raddebugger/assets/105329747/5aef21ff-025d-4a51-b1a9-47639a5c1122)
4. Then try to copy the "foobar" text using the keyboard shortcut Ctrl-C. The text is not copied to the clipboard buffer.

edit; actually it just seems like copying text via keyboard when a text cell is being selected doesn't work?

**Comment by ryanfleury** [comment]
Fixed in ed8731c09321bf86a6175ed517336418c36d6533.
