### ISSUE TITLE
Copy callstack

### ISSUE THREAD

**Issue by GloriousPtr** [EpicGamesExt/raddebugger#250]
It would be really nice to add a way to copy callstack.
Adding multiselect to copy callstack doesn't make much sense, maybe just a button to copy callstack would be better?

**Comment by ryanfleury** [comment]
Currently there is a way to do this, although not in the Call Stack view - you can just right-click a thread and click "Copy Callstack". But I will be doing a pass over the Call Stack view shortly to support more stuff like this.

**Comment by MohitSethi99** [comment]
That was helpful, thanks :)

**Comment by GloriousPtr** [comment]
Works well with multi row select with shift, closing this.
