### ISSUE TITLE
No rdi file gets created when degugging exe. No breakpoints can be set when generating rdi file manually.

### ISSUE THREAD

**Issue by JakWolf** [EpicGamesExt/raddebugger#251]
When trying to debug an exe, no rdi file gets created out of the pdb file. When creating a rdi file with rdi_from_pdb.exe i still can't set a breakpoint.
[fernwirkung.zip](https://github.com/user-attachments/files/15513997/fernwirkung.zip)

**Comment by ryanfleury** [comment]
Can you try this again with the latest on `master`? A number of big passes have been done over the format & converter in recent weeks (for inline info support), and your PDB is now converting fine for me.

**Comment by JakWolf** [comment]
Ok, it's working now.
