### ISSUE TITLE
Editing type cast in the watch window causes a Fatal Exception

### ISSUE THREAD

**Issue by BitShiftNow** [EpicGamesExt/raddebugger#253]
Version: 0.9.10 ALPHA - May 32 2024 [489ae56]

I have a simple C program that contains a 32-bit float. In the watch window (after hitting a breakpoint) I observed the value which is cast to a unsigned int as seen in this screenshot:
![Screenshot 2024-06-01 150609](https://github.com/EpicGamesExt/raddebugger/assets/125163623/2c0eb20f-1b1b-44bc-87eb-5ac4ca658538)

I then wanted to change the casting to something else so I started deleting characters from the type (cursor started right before the closing bracket). Right about when I was about to delete the i from the word int the Fatal Exception popped up:
![Screenshot 2024-06-01 150631](https://github.com/EpicGamesExt/raddebugger/assets/125163623/3553924b-0ce1-46fe-b69a-bf1eca34e6c5)

This is reproducible 100% of the time.
I am not sure what else to include in here so please let me know if you need more info. 

Oh and for some reason it shows 'Missing )' in the Value window as well.

**Comment by ryanfleury** [comment]
Fixed in 2c9a6f996dd7f1a4dddefa83d66bd338e6489c87.
