### ISSUE TITLE
AVX-512 instructions are not recognized in Disassembly window

### ISSUE THREAD

**Issue by michal-z** [EpicGamesExt/raddebugger#259]
Tested with 0.9.10 ALPHA.

**Comment by ratchetfreak** [comment]
duplicate of #169 

the disassembly library currently used doesn't support the newfangled x86 extensions.

**Comment by michal-z** [comment]
This issue is specifically about AVX-512. #169 is about AVX/AVX2.

**Comment by ratchetfreak** [comment]
same issue though, the OP in the issue literally says

> Quickly looking at the library, seems like there is no AVX-512 support either.

**Comment by ryanfleury** [comment]
Fixed as of ccf8504dd1209503905dfb97a0210f2a20e2acaa.
