### ISSUE TITLE
[Feature] Flush OutputDebugString when breaking in the debugger

### ISSUE THREAD

**Issue by TheSandvichMaker** [EpicGamesExt/raddebugger#261]
In my program, when I log something with the log level "Error" I have the option to break into the debugger right there. So first I call OutputDebugStringA("My error"), and then there's a __debugbreak(). In Visual Studio and RemedyBG, I can see my message in the debugger output window, but in raddbg I can't. It shows up only after I continue execution. It would be nice if raddbg could match the behaviour of VS/Remedy. 

NOTE: I think this is also why sometimes when I hit a debug break from the D3D12 debug layer, I can't see the validation message.

**Comment by ryanfleury** [comment]
This should be fixed in fb6689a74d2c9594f5f6b817aa0ab5fd9ef7987b. Let me know if you run into an issue with this again.
