### ISSUE TITLE
Source code tabs disappear when reopening debugger

### ISSUE THREAD

**Issue by GoldenbergDaniel** [EpicGamesExt/raddebugger#262]
I am on the master branch. This is not the case in the latest release, where the debugger would remember which source files were open. I think this behavior makes more sense, as it's annoying to have to reopen the source files every time I open the debugger.

**Comment by ryanfleury** [comment]
This should be fixed in 3c39a88abf65ae0c29982e82cdc295d1b1da4808. Let me know if you run into this again.
