### ISSUE TITLE
Fatal exception on hitting "Kill all target processes"

### ISSUE THREAD

**Issue by helviett** [EpicGamesExt/raddebugger#263]
Sometime when I hit "Kill all target processes" I get the following modal window:

<img width="419" alt="rad_crash" src="https://github.com/EpicGamesExt/raddebugger/assets/17850773/d637130d-c9b8-4a54-93a3-b9ac41fdf839">

**Comment by ryanfleury** [comment]
Can you provide more info about the context in which this is happening? How many processes are you running, what are you doing when you kill them? It would also help a lot to see the callstack, so if you can pull & build the debugger locally, it should show a callstack in that dialogue box, and that should help me track the issue down.

**Comment by helviett** [comment]
I run simple Vulkan application: load GLTF scene, render it with lights and shadows, validation layers are turned on, nothing fancy.
Can't figure out repro steps. I could caught it once and attach with VS debugger to see the call stack. On hitting "Kill all target processes" it hangs in `ctrl_unwind_from_thread`, keeps spinning eternal loop and allocates memory.

Call stack:
```
>	raddbg.exe!ctrl_unwind_from_thread(Arena * arena, CTRL_EntityStore * store, unsigned __int64 machine_id, DMN_Handle thread, unsigned __int64 endt_us) Line 2615	C
 	raddbg.exe!df_query_cached_unwind_from_thread(DF_Entity * thread) Line 6353	C
 	raddbg.exe!df_view_ui_CallStack(DF_Window * ws, DF_Panel * panel, DF_View * view, Rng2F32 rect) Line 4852	C
 	raddbg.exe!df_window_update_and_render(Arena * arena, DF_Window * ws, DF_CmdList * cmds) Line 6961	C
 	raddbg.exe!update_and_render(OS_Handle repaint_window_handle, void * user_data) Line 346	C
 	raddbg.exe!entry_point(CmdLine * cmd_line) Line 393	C
 	raddbg.exe!main_thread_base_entry_point(void(*)(CmdLine *) entry_point, char * * arguments, unsigned __int64 arguments_count) Line 84	C
 	raddbg.exe!w32_entry_point_caller(int argc, wchar_t * * wargv) Line 1841	C
 	raddbg.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, wchar_t * lpCmdLine, int nShowCmd) Line 1854	C
 	[External Code]
 ```
 
 Memory slowly goes higher and higher:
 
<img width="886" alt="Screenshot 2024-06-16 124515" src="https://github.com/EpicGamesExt/raddebugger/assets/17850773/dd4d4315-bb62-4571-b911-fc3e188e03d5">

**Comment by ryanfleury** [comment]
Can you try this again, after the 749821dd27c7abb0dd0fc7fb6088e3cf0303268c commit, and let me know if you run into it again? I don't know exactly what would cause the "unwind loop" to get caught like this, but I've now added a check for what is one possibly likely scenario when e.g. a process is killed, but I want to know if this is some other case also.

**Comment by ryanfleury** [comment]
Closing this, assuming this issue has been resolved, but just let me know if you see it again.
