### ISSUE TITLE
Exception thown: (Win32) Floating-Point Overflow

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#264]
Getting this exception even though it is disabled in exception filters
![image](https://github.com/EpicGamesExt/raddebugger/assets/29519295/4ada1a75-3798-4b4c-ad87-ab9734a4a471)

**Comment by ryanfleury** [comment]
This may be another manifestation of #190. Can you try this again and see if it is still occurring?
