### ISSUE TITLE
Program gets painfully slow with conditional breakpoints

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#265]
I noticed the target program gets painfully slow with conditional breakpoints, RemedyBG runs totally fine though.
Not sure if it's relevant but the part where I add the breakpoint is parallelized.

**Comment by ryanfleury** [comment]
Go ahead and try again with the top of `master`; there was a *ton* of slop in the important path here, added by my logging additions to the control thread, on top of the slop that was already there. Different people are getting different numbers comparing the new version to Remedy, but it should be roughly comparable now.

**Comment by MohitSethi99** [comment]
Improved significantly! Yeah It's roughly the same as RemedyBG now.
Also, just noticed the raw runtime speed of the attached program is around 125% of what I get in RemedyBG which is such a great  thing! Thanks :)
