### ISSUE TITLE
Clicking on top and bottom area of "code" and "output" views selects and scroll text

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#267]
Title says it all. Not a major inconvenience though.

https://github.com/EpicGamesExt/raddebugger/assets/29519295/8cb1f012-a027-4534-80e8-423b7fc835d2

**Comment by ryanfleury** [comment]
Fixed in 31d7be8f8a25b9ffa4bb4b88dc37e3ae5a10b857.

**Comment by MohitSethi99** [comment]
Noticed the same bug in memory view.

**Comment by ryanfleury** [comment]
Fixed in 4fc5b61676a86ec083a8103851ce583d3026339b.
