### ISSUE TITLE
PDBs(?) emitted from clang fail to show local variables

### ISSUE THREAD

**Issue by Zorkimer** [EpicGamesExt/raddebugger#269]
Compiled
```
int main () {
   int testVariable = 8008;
}
```
with the commands
```
call clang -v ctest.c -o c.exe -g -gcodeview
call clang-cl -v ctest.c -o c_cl.exe -g -gcodeview
```
(I invoked vcvarsall.bat before the clang-cl call)
and locals works normally in VS:
![2024-06-17-1718640194](https://github.com/EpicGamesExt/raddebugger/assets/95318050/e6a25833-ecf6-4051-b92a-96327072b864)
![2024-06-17-1718640199](https://github.com/EpicGamesExt/raddebugger/assets/95318050/53bc04ca-b3c1-4f1d-9846-f7b3acbedb2a)
but in raddbg:
![2024-06-17-1718639852](https://github.com/EpicGamesExt/raddebugger/assets/95318050/d7b4e991-4c7a-47ff-8e8d-957c3934845e)
![2024-06-17-1718639861](https://github.com/EpicGamesExt/raddebugger/assets/95318050/ef52ed43-2cb4-437b-aa10-d663782f74c1)
Both the cl and non-cl versions have this issue.

**Comment by ryanfleury** [comment]
Fixed in 0b3e3228d1feaa14ca8d4653859d6dc1d1a5c2e1.
