### ISSUE TITLE
Issues with stepping into and over certain functions

### ISSUE THREAD

**Issue by GoldenbergDaniel** [EpicGamesExt/raddebugger#271]
The following function seems to experience the worst of these issues. When I try to step into `transform_3f` (which will first go through `v3f`), it steps into the function but doesn't redirect to the source file containing the function and doesn't allow me to step though it unless I do an "assembly step" at least once, in which case it resumes normal behavior. Strangely, I am able to step into `r_push_vertex` which is also in its own source file.

Another possibly related issue is that sometimes just stepping over this code (or really any code) causes the debugger to reset its state back to the breakpoint. This one is rare and difficult to reproduce.

```c
void draw_sprite_x(Mat3x3F xform, Vec4F tint, TextureID tex, bool flash)
{
  R_Renderer *renderer = &global.renderer;
  r_use_texture(renderer, &global.resources.textures[TEXTURE_SPRITE]);
  r_use_shader(renderer, &global.resources.shaders[SHADER_SPRITE]);

  Vec3F p0 = transform_3f(v3f(-8.0f,  8.0f, 1.0f), xform);
  Vec3F p1 = transform_3f(v3f( 8.0f,  8.0f, 1.0f), xform); 
  Vec3F p2 = transform_3f(v3f( 8.0f, -8.0f, 1.0f), xform);
  Vec3F p3 = transform_3f(v3f(-8.0f, -8.0f, 1.0f), xform);

  // ...

  r_push_vertex(renderer, p0, tint, color, top_left);
  r_push_vertex(renderer, p1, tint, color, top_right);
  r_push_vertex(renderer, p2, tint, color, bot_right);
  r_push_vertex(renderer, p3, tint, color, bot_left);
  r_push_quad_indices(renderer);
}
```

**Comment by ryanfleury** [comment]
The step-into issue has been fixed in 6eef8c3e16219863c68d419aa5c3047c788e5cbf. The stepping failure issue has been fixed in 435877824a7fcc56ad1d860c700d85685a7e944a.
