### ISSUE TITLE
Program crashes when right-clicking on certian tabs to close them like breakpoints and targets

### ISSUE THREAD

**Issue by KarimZoPr0** [EpicGamesExt/raddebugger#274]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Call stack:
1. [0x7ff6d8ff00cf] df_view_is_project_filtered +47, df_gfx.c line 81
2. [0x7ff6d901e0c4] df_window_update_and_render +170660, df_gfx.c line 7303
3. [0x7ff6d9063b1b] update_and_render +4171, raddbg.c line 335
4. [0x7ff6d8ed993a] entry_point +4906, raddbg_main.c line 393
5. [0x7ff6d8ed483d] main_thread_base_entry_point +381, base_entry_point.c line 84
6. [0x7ff6d9066279] w32_entry_point_caller +425, os_core_win32.c line 1842
7. [0x7ff6d8ec5036] wWinMain +54, os_core_win32.c line 1854
8. [0x7ff6d908135e] __scrt_common_main_seh +262, exe_common.inl line 288
9. [0x7ffd40d5257d] KERNEL32
10. [0x7ffd4294af28] ntdll

Version: 0.9.11 [c05ceed]

![image](https://github.com/EpicGamesExt/raddebugger/assets/58335539/37d95666-14eb-47ce-a86a-0bf2b44bbc54)

![image](https://github.com/EpicGamesExt/raddebugger/assets/58335539/8d86e8a2-45ad-4d62-bcb1-88b41ecbbceb)

**Comment by ryanfleury** [comment]
Fixed in 8ca67ff892855263f3b476e8eb379501a995a108.
