### ISSUE TITLE
Weird output behaviour

### ISSUE THREAD

**Issue by DevAgu93** [EpicGamesExt/raddebugger#278]
I expect the output to scroll, but it stays on top and sometimes it refreshes:

https://github.com/EpicGamesExt/raddebugger/assets/63572671/65a26bc1-cecf-4ed1-812c-38b0cf8e39d0

**Comment by FaultyPine** [comment]
Also experiencing this

**Comment by ryanfleury** [comment]
These issues should now be resolved on `dev`, and the fixes will be in 0.9.12. I wouldn't recommend switching to `dev` pre-emptively, as there are some changes which may currently break your configuration, but there will be a release shortly with these issues fixed.
