### ISSUE TITLE
Inactive panel overlay becomes fully opaque on restart after setting alpha to 0

### ISSUE THREAD

**Issue by TheSandvichMaker** [EpicGamesExt/raddebugger#279]
I don't like the inactive panel overlay (where I last clicked and where my eyes currently want to look are not meaningfully correlated), so I set its alpha to 0 in the theme. But when I restart raddbg, it instead seems to end up fully opaque:

![image](https://github.com/EpicGamesExt/raddebugger/assets/49493579/b55e87ad-5a10-4edc-b5f7-22dd3780d348)

The color in the theme still reports an alpha of 0, but I have to set it to something non-0 and then back to 0 to fix it. Also, the RGB values say 0, 0, 0 but obviously the color seen here is not pure black

This is on 0.9.11 ALPHA Jun 30 2024 [f03d0fb]

**Comment by ryanfleury** [comment]
Fixed in aed9a285f57869df995d9b63a44bf83208d4f5ab.
