### ISSUE TITLE
Text from source view mouse hover popup gets copied instead of selected source text.

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#280]
When attempting to copy selected text from the source view, if the mouse hover popup is open for that variable the text from the hover popup gets copied to clipboard instead of the selected text.

For example if I selected the variable "blah" the mouse hover popup will appear immediately. If I try to copy the text, the value "blah {123, 456}" is copied instead of the value "blah". If this is the intended behavior it would be great if there was an option to disabled it.

![image](https://github.com/EpicGamesExt/raddebugger/assets/105329747/c26ab7e7-7e00-4f5e-9d3f-a63b556982bc)

**Comment by ryanfleury** [comment]
This should feel better as of 3bb8dc9089e458f3cc7cd5d6b78b38880e63d891. Keyboard focus on the hover evaluation popup now requires manual interaction; unless this happens, keyboard focus (including cursor controls and copy/paste) will be kept on the underlying panel.
