### ISSUE TITLE
On every step a new file tab is open

### ISSUE THREAD

**Issue by detter-dev** [EpicGamesExt/raddebugger#281]
Stepping opens the same file tab and it scrolls down to the current execution line. I tried full delete and clone again, but it's still happening.

https://github.com/EpicGamesExt/raddebugger/assets/100287158/70443d4f-5d5a-4036-b2d5-ce1466e10009

**Comment by ryanfleury** [comment]
This is likely being caused by a malformed row in the "File Path Map". I am not sure how these are sometimes being generated, but deleting that row should fix the issue for you.

**Comment by detter-dev** [comment]
Awesome, it worked, thank you.

**Comment by ryanfleury** [comment]
I've done a few major passes over the file path map & config system as of 0.9.13, and it should have made the debugger robust to this issue, but if it happens again please just re-open the issue and let me know.
