### ISSUE TITLE
Crash when held F5 to skip some asserts

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGamesExt/raddebugger#288]
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGames/raddebugger/issues

Call stack:
1. [0x7ff68c5fb3e8] df_view_ui_Code +5560, df_views.c line 6579
2. [0x7ff68c6ba58d] df_window_update_and_render +174077, df_gfx.c line 7282
3. [0x7ff68c7444ca] update_and_render +4698, raddbg.c line 335
4. [0x7ff68c6ce378] entry_point +6888, raddbg_main.c line 393
5. [0x7ff68c6e3b67] main_thread_base_entry_point +887, base_entry_point.c line 84
6. [0x7ff68c746938] wWinMain +360, os_core_win32.c line 1855
7. [0x7ff68c747b2a] __scrt_common_main_seh +262, exe_common.inl line 288
8. [0x7fffba08257d] KERNEL32
9. [0x7fffbb1eaf28] ntdll

Version: 0.9.11 [d78afc5]

[Close]

**Comment by ryanfleury** [comment]
Fixed in 044e78bea21095203029e29db6766a84a9e41b4b.
