### ISSUE TITLE
"Goto line" not taken into account for "Run to cursor" if raddbg does not have focus

### ISSUE THREAD

**Issue by rjurga** [EpicGamesExt/raddebugger#289]
# Summary

If you run a `goto_line` command followed by a `run_to_cursor` command while raddbg is not the window which has focus on the desktop, then `run_to_cursor` runs to where the cursor last was when raddbg had focus, instead of where `goto_line` moved the cursor to.

# Steps to reproduce

1. Open a file in raddbg.
2. Take note of the line where the cursor is.
3. Open cmd.exe and put its window in front of raddbg, so that it has the focus but raddbg has not.
4. Run `raddbg --ipc goto_line <some_other_line_number>`. In the background, you can notice the cursor move to that line, but it will be red (with default theme) because there is no focus.
5. Run `raddbg --ipc run_to_cursor`. It will run to the cursor position of step 2, not that of step 4.

If instead, after step 4, you alt tab to raddbg, alt tab back to cmd.exe, and then do step 5, it will run to the new cursor position.

**Comment by rjurga** [comment]
By the way, the issue also occurs with `find_code_location` instead of `goto_line`.

**Comment by ryanfleury** [comment]
Fixed in ebbf927fc160f1fda47210c548306d2405345fac.
