### ISSUE TITLE
Bring debugger to foreground on exception

### ISSUE THREAD

**Issue by michalev-k** [EpicGamesExt/raddebugger#294]
When raddbg is running minimized, on hitting an exception, I would like raddbg to come to the foreground and jump to where it was hit. 
I start raddbg with ipc, and would like it to stay in the background, unless the above occurs. 
Currently it just stays minimized, not jumping anywhere.

**Comment by ryanfleury** [comment]
Fixed as of 534a727b7ca16d4bf1214e8192b97461e04e348c. This is currently on `dev` and will shortly be in the 0.9.12 release.
