### ISSUE TITLE
Watch can't evaluate member variable

### ISSUE THREAD

**Issue by GloriousPtr** [EpicGamesExt/raddebugger#296]
Its not just *this* scope, cant evaluate any member variable in any struct
PS: Same with hover
version: 0.9.12 ALPHA 44fb752
![image](https://github.com/user-attachments/assets/477197e9-5206-44d7-9891-bee833c0d322)

**Comment by ryanfleury** [comment]
Is this still happening after the other various `this` fixes?

**Comment by ryanfleury** [comment]
(Checked via Discord, all fixed up now!)
