### ISSUE TITLE
Crash on step into inlined function

### ISSUE THREAD

**Issue by GloriousPtr** [EpicGamesExt/raddebugger#298]
Here is the minimal repro:
https://1drv.ms/u/s!ApjsIRdEL5T4kyAJweDx7qMSHwvW?e=CdUkNc

https://github.com/user-attachments/assets/745df007-d09d-4594-9ecf-7d1f990b8667

**Comment by ryanfleury** [comment]
Fixed in eda3d6f8b5241aa05d7041c2d833e81e48447e0b.
