### ISSUE TITLE
Debugger shows wrong values for const negative int32_t in watch window

### ISSUE THREAD

**Issue by rtarun9** [EpicGamesExt/raddebugger#304]
Hey, when using the latest release of the rad debugger (0.9.11 ALPHA - Jun 26 2024 [c05ceed]) I noticed that the watch window shows wrong values for negative int32_t's.

For example, with the code:
```c
#include <stdint.h>
#include <stdio.h>

int main() {
  const int32_t x = 3;
  const int32_t y = -10;

  const int32_t z = x + y;

  printf("%d ", z);
}
```

The debugger's watch window shows the following values:
![image](https://github.com/user-attachments/assets/97a5d454-3071-425e-b5b2-fd974739361a)
You can see that wrong values are reported for y and z.

The console / terminal when the app is run shows the correct output value of z.

Also, notice how when const is removed from y, the watch windows shows the correct value of -10, but shows the same incorrect value for z (which is still const):
![image](https://github.com/user-attachments/assets/335de031-81c4-4630-8b8b-61d69692678c)

To get the correct value in watch window for all variables, I need to remove const entirely:
![image](https://github.com/user-attachments/assets/552cfc7c-23ed-454b-87b1-15197c9e20fd)

To compile the code, I used `clang --debug main.c`. The same issue occurs when compiling with cl.exe

**Comment by ryanfleury** [comment]
This is now fixed as of 0.9.13; let me know if you run into the same issue again.
