### ISSUE TITLE
Watch window doesn't allow casting values to size_t

### ISSUE THREAD

**Issue by rtarun9** [EpicGamesExt/raddebugger#307]
Hey, I have noticed that when using the watch window in the latest release (0.9.11 ALPHA - Jun 26 2024 [c05ceed], I am able to case variables to a number of different data types like int, int64_t, int32_t, int16_t, uint64_t, etc.
However, I am not able to cast values into a size_t datatype.

![image](https://github.com/user-attachments/assets/a9337fdd-9667-4bab-b7a0-8f585c3b41d9)

**Comment by ryanfleury** [comment]
`size_t` added in `dev`; this will be in 0.9.12.
