### ISSUE TITLE
Watch window shows wrong ASCII value for escape sequences

### ISSUE THREAD

**Issue by 0xd61** [EpicGamesExt/raddebugger#308]
When using escape sequences, the wrong ASCII value is shown in the watch window and in code (when hovering the expression).

'\n'
Expected: 10
Got: 92

'\t'
Expected: 9
Got: 92

![image](https://github.com/user-attachments/assets/5d7008ac-0350-4ce7-9999-be2de094c3ac)

It seems like the values are not treated as escape sequences but a simple backslash.

**Comment by ryanfleury** [comment]
This is now fixed as of 0.9.13.
