### ISSUE TITLE
Seemingly "incorrect" instructions in the disassembly window

### ISSUE THREAD

**Issue by amanKharb10** [EpicGamesExt/raddebugger#310]
Hello,

I noticed an issue with the disassembly window. I'm quite new to disassembly and I was just exploring some things when I noticed that rad dbg outputs seemingly "incorrect" instructions for the fma call that I made, while MSVC shows the fmadd instruction that I expected.

The exe was compiled using these flags:
/MT /GR- /GL /EHa- /O2 /Oi /W2 /Zi /arch:AVX2

Sorry if something related to this had already been posted. I searched for assembly related issues but couldn't see something similar so decided to report.

RAD DBG:
![raddbg](https://github.com/user-attachments/assets/efc95e20-5343-4c5e-847b-2fec5f5b179d)

MSVC:
![MSVC](https://github.com/user-attachments/assets/e5dd4080-72e7-480f-b781-349759d70825)

**Comment by ryanfleury** [comment]
I think this is related to the other previously reported disassembly issues (one being #259), which have been fixed (but not pushed into a release yet)—which version are you using?

**Comment by amanKharb10** [comment]
I'm on 0.9.11 alpha
