### ISSUE TITLE
Default View Rule for specific Type

### ISSUE THREAD

**Issue by Adarma** [EpicGamesExt/raddebugger#312]
Can we set a default View Rule for specific Types?

For example I have a v3 struct with a union of (x, y, z), (r, g, b), (xy, z).
I would like to have the View Rule default to `only:(x, y, z)` for all v3 types to reduce the union duplication clutter without having to type it in every time.

Thanks

**Comment by ryanfleury** [comment]
Yep, this will almost certainly be in 0.9.12.

**Comment by ryanfleury** [comment]
This is now done; there will be more work on this feature to support things like templates and more view rule possibilities, but this basic case is supported now.

**Comment by fbjerno** [comment]
Is is possible to access member variables in auto view rules, e.g `Image -> bitmap:(w:Image.w, h:Image.h, fmt:rgba8)`?
