### ISSUE TITLE
Missing call stack frames because adjusted_frame_base not applied during PE_UnwindOpCode_SET_FPREG

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#313]
I encountered this bug when debugging V8. You can reproduce it in V8 by using the arguments "--shell --allow-natives-syntax" and then typing "%SystemBreak();" into the d8 shell. 

The callstack contains missing (and incorrect) stack frames.

![image](https://github.com/user-attachments/assets/c6b31301-0700-42ff-93ad-df807cfa9039)

I had a look and it seems the issue is that in the case that [adjusted_frame_base  == raw_frame_base](https://github.com/EpicGamesExt/raddebugger/blob/eda3d6f8b5241aa05d7041c2d833e81e48447e0b/src/ctrl/ctrl_core.c#L2270) the frame_base won't be updated properly for the [PE_UnwindOpCode_SET_FPREG opcode](https://github.com/EpicGamesExt/raddebugger/blob/eda3d6f8b5241aa05d7041c2d833e81e48447e0b/src/ctrl/ctrl_core.c#L2365). An off-by-one.

Removing the check seems to fix it.
```
        //if(adjusted_frame_base < raw_frame_base)
        {
          frame_base = adjusted_frame_base;
        }
```

![image](https://github.com/user-attachments/assets/2bd0de85-f3b6-40a8-8a37-78323d12ad4a)

**Comment by ryanfleury** [comment]
Thanks for looking into this; fixed as of 64e5d60f380dcc046905e47d7589bfbb8d483119. This will be in 0.9.12.
