### ISSUE TITLE
crash while debugging, no more info than that

### ISSUE THREAD

**Issue by ocohen** [EpicGamesExt/raddebugger#316]
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGamesExt/raddebugger/issues

Call stack:
1. [0x7ff7582fdf16] e_expr_push_child +86, eval_parse.c line 744
2. [0x7ff75830169e] e_parse_expr_from_text_tokens__prec +3710, eval_parse.c line 1139
3. [0x7ff758304f5f] e_parse_expr_from_text_tokens +95, eval_parse.c line 1883
4. [0x7ff75830b8f3] e_eval_from_string +163, eval_bundles.c line 11
5. [0x7ff758406ac2] df_code_slice +33122, df_gfx.c line 12148
6. [0x7ff758409b88] df_code_slicef +248, df_gfx.c line 12563
7. [0x7ff758418d8e] df_code_view_build +11278, df_views.c line 939
8. [0x7ff75839a9c9] df_view_ui_Code +4825, df_views.c line 6447
9. [0x7ff7583e2bbe] df_window_update_and_render +176750, df_gfx.c line 7265
10. [0x7ff758428ee4] update_and_render +4292, raddbg.c line 342
11. [0x7ff758298de6] entry_point +4838, raddbg_main.c line 392
12. [0x7ff758294809] main_thread_base_entry_point +345, base_entry_point.c line 82
13. [0x7ff75842bdc0] w32_entry_point_caller +2320, os_core_win32.c line 1632
14. [0x7ff758285036] wWinMain +54, os_core_win32.c line 1644
15. [0x7ff75845910e] __scrt_common_main_seh +262, exe_common.inl line 288
16. [0x7ff8e6507374] KERNEL32
17. [0x7ff8e74fcc91] ntdll

Version: 0.9.12

[Close]

**Comment by ryanfleury** [comment]
This has been fixed on `dev`. I don't yet recommend pulling/building from there for actual usage, since there are a few things I have broken while doing some major passes. But this fix will be in the 0.9.12 release.

**Comment by ocohen** [comment]
Awesome, thank you
