### ISSUE TITLE
Fatal Exception  (code 0x80000003) 

### ISSUE THREAD

**Issue by a98c14** [EpicGamesExt/raddebugger#318]
<img width="279" alt="{6ADFF90D-D164-41E8-9E37-AAC08350A68B}" src="https://github.com/user-attachments/assets/178f897f-bb51-435b-85a8-62403b8403b7">

I don't exactly know what caused it.  I got the error while I was fiddling with stuff in the watch window (dereferencing from memory address etc.). I can't launch the debugger to confirm.

[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0x80000003) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGamesExt/raddebugger/issues

Call stack:
1. [0x7ff616e29570] df_eval_memory_read +48, df_core.c line 3831
2. [0x7ff616dccc92] e_value_eval_from_eval +626, eval_bundles.c line 156
3. [0x7ff616ead224] df_single_line_eval_value_strings_from_eval +1780, df_gfx.c line 8486
4. [0x7ff616eadfa3] df_single_line_eval_value_strings_from_eval +5235, df_gfx.c line 8583
5. [0x7ff616eafeb1] df_eval_viz_windowed_row_list_from_viz_block_list +2017, df_gfx.c line 8892
6. [0x7ff616ee3af8] df_watch_view_build +29976, df_views.c line 2341
7. [0x7ff616e5d8c8] df_view_ui_Watch +168, df_views.c line 6783
8. [0x7ff616ea4335] df_window_update_and_render +177765, df_gfx.c line 7264
9. [0x7ff616eeaa82] update_and_render +4306, raddbg.c line 342
10. [0x7ff616d59224] entry_point +4852, raddbg_main.c line 392
11. [0x7ff616d54c1a] main_thread_base_entry_point +346, base_entry_point.c line 82
12. [0x7ff616eed977] w32_entry_point_caller +2327, os_core_win32.c line 1631
13. [0x7ff616d453f6] wWinMain +54, os_core_win32.c line 1644
14. [0x7ff616f1aeee] __scrt_common_main_seh +262, exe_common.inl line 288
15. [0x7ffb1832257d] KERNEL32
16. [0x7ffb1950af28] ntdll

Version: 0.9.12 [86f45ce]

[Close]

### **Edit**
I found out where watch info is stored, below is the one that is causing the crash. After deleting it I can launch the debugger without a problem. Also crash occurs right when I stop the debugger (watch works fine while it is running), I can reproduce it.
```
watch:
{
  expression:  "(int*)(0xe55b0f970)"
  view_rule:   ""
}
```

**Comment by ryanfleury** [comment]
Fixed in `dev`; this will be in 0.9.12.
