### ISSUE TITLE
Search box doesn’t eat unmodified key events

### ISSUE THREAD

**Issue by drpriver** [EpicGamesExt/raddebugger#319]
Steps to reproduce:

1. Add a keybinding without a modifier key (like `{"step_over"   n}`)
2. Start a search (ctrl-f)
3. Type an `n` with the search box open. It will execute step_over in addition to putting an `n` in the search box.

**Comment by ryanfleury** [comment]
This is fixed on `dev` as of 95dd544871aee79905d6c1f65a9033576485ca43 and will be in 0.9.12.
