### ISSUE TITLE
Single character hotkeys are triggered when editing a text field

### ISSUE THREAD

**Issue by markersniffen** [EpicGamesExt/raddebugger#324]
Single character hotkeys are triggered when editing a text field. For example, I have `Run` bound to the key `g`. If I am trying to open a file and type `g` into the text box, `Run` is triggered.

**Comment by ryanfleury** [comment]
This is fixed on `dev` as of 95dd544871aee79905d6c1f65a9033576485ca43 and will be in 0.9.12.
