### ISSUE TITLE
[Feature request] command line flag to close the debugger after --auto_run

### ISSUE THREAD

**Issue by ustance** [EpicGamesExt/raddebugger#325]
Analogues to -q flag in RemedyBG.

My usecase is that I launch a game with debugger by default via a text editor and currently have to close the debugger manually after closing the game. I can keep debugger alive all the time and use IPC, but it would be really neat to have a flag like that.

Btw, really enjoying the debugger so far, thanks for your work!

**Comment by ryanfleury** [comment]
Added to `dev` as of 2bf5c9c9a4e4dfe217d3d032430ffbd370c3596e. I wouldn't recommend switching to that branch at the moment, since it is still pre-release and may break your configuration (although aside from that it's mostly functional), but either way this will be in 0.9.12 fairly soon.
