### ISSUE TITLE
Disambiguate files with same name in the tab bar

### ISSUE THREAD

**Issue by namandixit** [EpicGamesExt/raddebugger#330]
When multiple files are opened, the title of each tab is set equal to the name of the file. However, if two files have the same name, this makes thing confusing. One disambiguating scheme that could be used is to copy Emacs that scans each path back one folder at a time until it finds the folder whose name doesn't clash, and then adds that folder's name to the tab name. For example, two files with the path `C:/a/b/c/d.txt` and `P:/a/e/c/d.txt` will be shown as `d.txt <b>` and `d.txt <e>` respectively.

**Comment by ryanfleury** [comment]
Done in 9c1f8ef37b7ab450284f8183a163ca01bde5fdd0.
