### ISSUE TITLE
Stepping brings the disassembly view to the foreground.

### ISSUE THREAD

**Issue by philipkatis** [EpicGamesExt/raddebugger#331]
When hitting a breakpoint or doing any form of stepping, the disassembly view automatically comes to the foreground of the panel it is part of. If multiple disassembly views are open, only the first one is brought to the foreground. If no disassembly views are open, stepping works as expected.

For example, I like having the disassembly view in the same panel as the watch view. So every time I change something in the watch view and step, the disassembly view comes to the foreground. Since the focus was on that panel, the step happens in the disassembly and not the source code.

**Comment by ryanfleury** [comment]
I've adjusted this in 38173a71548f96fa74add1e51f9ad49c0d03462c. There is not really a right answer here; some people want disassembly snaps at all times, some people don't. To account for this, after that change, I only require a disassembly snap/selection when a code location is being snapped to without any file/line info. So for example, if you click on a call stack frame with no debug info, or if you step into a function for which you have no debug info, it will snap to disassembly. If disassembly is selected, then it will snap. If a disassembly tab is not focused, however, it will not snap to disassembly unless it has to, given the previously stated conditions.
