### ISSUE TITLE
Paths with single backslashes passed as command-line inputs are not displayed properly

### ISSUE THREAD

**Issue by rjurga** [EpicGamesExt/raddebugger#332]
When I run this command:
```
raddbg --ipc find_code_location "C:\Projects\Wolves-jai\src\input.jai:2"
```
the file is found and open in a new tab, but in the tab title the backslashes are interpreted like escapes, I think.
![image](https://github.com/user-attachments/assets/bdc2db8b-b08d-45b9-81ad-7247f94f78de)

And at the bottom of the code window they're displayed like unknown characters:
![image](https://github.com/user-attachments/assets/b5824254-a054-45cb-a11e-017b91e06165)

If I replace all the backslashes by `\\` or `/` then the file is also found, and its name is displayed properly. So I don't know if single backslashes are not supported but the failure mode is ambiguous given that the files are found and opened.

**Comment by ryanfleury** [comment]
It's kind of entertaining that it found the file correctly...

But anyways, this should work better as of 938af75efb263d1235b626972dfd4ac928eb803f. Let me know if you run into any more issues with it.
