### ISSUE TITLE
HighDpi UIScale is not taken into account anymore

### ISSUE THREAD

**Issue by tdecroyere** [EpicGamesExt/raddebugger#341]
Hello, 

Thanks for this excellent tool, I use it all the time!

With the latest 2 versions, I see that it doesn't take into account the scaling factor set in Windows 11 screen settings. 

I have a 4K monitor and I usually set the scaling factor to 150%. 
All is working well with version v0.9.11-alpha.

This is what is displayed in version v0.9.11-alpha:
![RadDebugger-v0 9 11-alpha](https://github.com/user-attachments/assets/39be1c68-e25b-4277-b7a9-474d1a60e279)

This is what is displayed in the latest version v0.9.13-alpha:
![RadDebugger-v0 9 13-alpha](https://github.com/user-attachments/assets/077600b7-eb1d-4b28-969e-58ab8787dfdb)

As you can see, it doesn't seems to take into account the scaling factor anymore.

**Comment by ryanfleury** [comment]
Yeah - this is a matter of bad defaults, I wanted to shift the font sizing state to being precise sizes, and as a result I don't initialize correctly for different DPIs anymore (it used to be delta-based). If you zoom in to your liking (via Ctrl + Scroll), it should retain that setting correctly (you can do it for the UI and source code independently).

**Comment by ryanfleury** [comment]
The default font sizes have been adjusted as of 8994cb04bc2900dcbbd0bbe04e7121175f9b8393 to account for different DPIs on first-time startup.
