### ISSUE TITLE
IPC run_to_cursor command is broken

### ISSUE THREAD

**Issue by rjurga** [EpicGamesExt/raddebugger#343]
Hi. Running
```
raddbg --ipc run_to_cursor
```
doesn't work anymore as of v0.9.13-alpha. It worked in v0.9.12-alpha.

Doing ctrl+F10 in raddbg still works, so it's just the ipc command.

It does start the exe but just doesn't stop at the cursor location.

**Comment by ryanfleury** [comment]
`run_to_cursor` has been eliminated as a command, and has been replaced by `run_to_line`, which both works for the cursor position, and explicit parameterization (two commands became one). You can use that command instead, and either use the last stored cursor position, or explicitly parameterize it with a file/line.
