### ISSUE TITLE
Is it planned to allow custom visualizers?

### ISSUE THREAD

**Issue by simonvanbernem** [EpicGamesExt/raddebugger#344]
Hi!

In my game, I'm generating quite a lot of gameplay-relevant polygons and if that goes wrong for some reason I want to debug them. This usually involves plotting the polygon on a 2D plane and allowing to zoom and pan around, add additional points, move points around and so on. It would be great, if I could have such a tool in the debugger, so that I didn't need to serialize the polygons and copy them to some other tool.

Since the specifics of my need are probably VERY niche, having such a thing built into the debugger may not be worth the trouble. I could imagine many more visualization (something akin to https://kaitai.io/ for example), that would be very helpful to me, but maybe too niche to be worth the maintanace burden for the debugger itself. Thus I wondered, if it is planned to allow for the integration of custom visualizers. If there was some API to integrate my custom UI code into raddbg, I would be happy to write that code.

Since raddbg is open source, forking and adding my own visualizer would of course be possible, but if there is no clear API boundary that runs the risk of trouble when updating. Thus my question:

**Is it planned to have an API of some kind that custom visualizers could hook into, allowing them to be used like any built-in visualizer?**

**Comment by ryanfleury** [comment]
Yes, that is all planned; ideally it can get to the point where your EXE itself can just define the visualization code, so there is no special build to do. The debugger will have built-in visualizers for things like plotting points, 2D/3D geometry, and so on, but they will just be included visualizers which click into the same visualization system that custom code would. The full custom visualizer story is still a ways out, but that is one of the things that we're building toward.
