### ISSUE TITLE
Crash when going to a function when attached to Unreal Editor 4.27

### ISSUE THREAD

**Issue by Takao-7** [EpicGamesExt/raddebugger#347]
Steps to reproduce:

1. Start the Unreal Editor through Rider, WITHOUT an attached debugger
2. Attach raddebugger to the editor
3. Search for a class name in your project with "Go To Name"
4. Select any function of that class (I selected "BeginPlay()")
==> Crash

> [Window Title]
> Fatal Exception
> 
> [Content]
> A fatal exception (code 0xc0000005) occurred. The process is terminating.
> 
> Press Ctrl+C to copy this text to clipboard, then create a new issue at
> https://github.com/EpicGames/raddebugger/issues
> 
> Call stack:
> 1. [0x7ff6ceea0229] str8_skip_last_slash +89, base_strings.c line 994
> 2. [0x7ff6cefa8bfa] df_view_ui_Code +5130, df_views.c line 6584
> 3. [0x7ff6cefefbed] df_window_update_and_render +173133, df_gfx.c line 7283
> 4. [0x7ff6cf036782] update_and_render +4226, raddbg.c line 335
> 5. [0x7ff6ceea98fa] entry_point +4906, raddbg_main.c line 393
> 6. [0x7ff6ceea47fd] main_thread_base_entry_point +381, base_entry_point.c line 84
> 7. [0x7ff6cf038ee9] w32_entry_point_caller +425, os_core_win32.c line 1842
> 8. [0x7ff6cee95036] wWinMain +54, os_core_win32.c line 1854
> 9. [0x7ff6cf05412e] __scrt_common_main_seh +262, exe_common.inl line 288
> 10. [0x7ffe45c7dbe7] KERNEL32
> 11. [0x7ffe475c5a4c] ntdll
> 
> Version: 0.9.11 [d78afc5]
> 
> [Close]

**Comment by ryanfleury** [comment]
Can you update to 0.9.13 and try this again?

**Comment by ryanfleury** [comment]
Yeah, there are still usability problems with UE or UE-sized codebases, it isn't quite there yet.
