### ISSUE TITLE
RAD Linker can't find mt.exe even if its in the same folder as radlink.exe

### ISSUE THREAD

**Issue by santagada** [EpicGamesExt/raddebugger#349]
radlink.exe can't find mt.exe if I put it right next to radlink.exe, also can't find it if I put /RAD_MT_PATH="<path>" as an absolute path to the radlink.exe folder.

**Comment by NikitaSmith057** [comment]
/RAD_MT_PATH should contain full path to mt.exe including executable name. When I run linker from console that has environment setup with vcvarsall, the switch is set to /RAD_MT_PATH:"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\mt.exe". And if you want linker to pick up mt.exe that is in the same folder you can set /RAD_MT_PATH="mt.exe".
