### ISSUE TITLE
bitfield value is not shown correctly.

### ISSUE THREAD

**Issue by lch32111** [EpicGamesExt/raddebugger#355]
Hello

I am using the latest raddebugger (v0.9.13 ALPHA, released in  Oct 18 2024).
My struct just simply has two u64 integers with 63 bit and 1 bit fields.

When I debug my application,  raddebugger does not show correct values.
![image](https://github.com/user-attachments/assets/c3ec4432-629e-414f-a589-19710c30becf)

As you can see on the screenshot, the actual value of `block->size` is 524288, but in the debugger, it's '9223372036855300096'. I deleted .rdi file and debugged again, but it shows the same wrong value.

**Comment by ryanfleury** [comment]
Fixed in c42e7837ac704fa61bef2465b625d56952e0140c.
