### ISSUE TITLE
[Bug] Deadlock in filestream layer

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#358]
On commit d036eb9fc5f893d25d7b122fb51d4be4c23c0316. 
I am experiencing a deadlock involving the file stream layer. Sorry I don't have a minimal repro yet.
Seems related to the recent [eliminate r/w lock promotion concept](https://github.com/EpicGamesExt/raddebugger/commit/44b8c9e87cc95f73ce778fe988458c764b6866b6) commit.

**Main thread:**
os_rw_mutex_take_r
[fs_size_from_path](https://github.com/EpicGamesExt/raddebugger/blob/d036eb9fc5f893d25d7b122fb51d4be4c23c0316/src/file_stream/file_stream.c#L234)
e_irtree_and_type_from_expr
e_eval_from_expr
e_eval_from_string
rd_file_path_from_eval_string
rd_frame
frame
update
entry_point
main_thread_base_entry_point
w32_entry_point_calle
wWinMain

**[async] work thread #0**
os_rw_mutex_take_w
[fs_stream_work](https://github.com/EpicGamesExt/raddebugger/blob/d036eb9fc5f893d25d7b122fb51d4be4c23c0316/src/file_stream/file_stream.c#L360)
async_execute_work
async_push_work_
[fs_hash_from_path_range](https://github.com/EpicGamesExt/raddebugger/blob/d036eb9fc5f893d25d7b122fb51d4be4c23c0316/src/file_stream/file_stream.c#L159)
[fs_key_from_path_range](https://github.com/EpicGamesExt/raddebugger/blob/d036eb9fc5f893d25d7b122fb51d4be4c23c0316/src/file_stream/file_stream.c#L193)
dasm_parse_work
async_execute_work
async_work_thread__entry_point
os_w32_thread_entry_point

**[fs] detector thread**
os_rw_mutex_take_r
[fs_detector_thread__entry_point](https://github.com/EpicGamesExt/raddebugger/blob/d036eb9fc5f893d25d7b122fb51d4be4c23c0316/src/file_stream/file_stream.c#L417)
os_w32_thread_entry_point

**Comment by ryanfleury** [comment]
No problem, yep I think I thought this change through poorly - working on a fix now.
