### ISSUE TITLE
[Bug] Stale value in selected watch value after updating

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#365]
```
#include <stdio.h>
#include <stdint.h>
 
int main(void) {
    uint32_t a = 0x1111;
    uint32_t b = 0x2222;
    
    uint32_t *ptr = &a;
    
    int let_me_break = 3;
    
    ptr = &b;
     
    return 0;
}
```

Place a breakpoint on lines 10 and 14. 
![image](https://github.com/user-attachments/assets/37d16304-fcb5-4726-a6c8-d927b6c4d2b2)

Run the program. When stopped on line 10 enter the "ptr" value in the watch view and select the value field.
![image](https://github.com/user-attachments/assets/735f33f7-75d0-48f2-965b-1c5760bcd84d)

Run the program. When stopped on line 14 - the "ptr" value still contains the old value. This is confusing behavior to me. I realize you can get the actual value back by pressing escape but it would be preferable if the value updated automatically.
![image](https://github.com/user-attachments/assets/d1ca8d6e-39f5-408f-9fb7-988b4de54de2)

**Comment by ryanfleury** [comment]
This is working as intended, and is not a bug. When you double click the value cell, you begin an editing operation, and during an editing operation the user is in control of their cursor, selection, and the text that they are editing. In many cases, it is not well-defined how the debugger would update the text while the user is editing it, given that many things might change (the type of the evaluation & thus the syntax of the displayed value, the length in characters of the displayed value, and so on). In cases (like this one) where you could imagine a rule where it updates the text (e.g. when the user has not modified the value, and the length is the same, and/or the selection encloses the entire field), this rule does not apply universally, and so I think adding it would make the interface more idiosyncratic and more confusing.
