### ISSUE TITLE
Fatal exception when adding [rdx+0x40] to the watch window

### ISSUE THREAD

**Issue by TomTetlaw** [EpicGamesExt/raddebugger#378]
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGamesExt/raddebugger/issues

Call stack:
1. [0x7ff6b197450d] memcpy +381, memcpy.asm line 292
2. [0x7ff6b1886210] rd_eval_space_read +1968, raddbg_core.c line 2268
3. [0x7ff6b189002b] e_value_eval_from_eval +347, eval_bundles.c line 159
4. [0x7ff6b1909d4d] rd_append_value_strings_from_eval +3117, raddbg_core.c line 9319
5. [0x7ff6b18ff50d] rd_value_string_from_eval +269, raddbg_core.c line 9639
6. [0x7ff6b194f5b5] rd_string_from_eval_viz_row_column +1349, raddbg_views.c line 1053
7. [0x7ff6b194570f] rd_watch_view_build +45263, raddbg_views.c line 2873
8. [0x7ff6b17f01ed] rd_view_rule_ui_watch +1037, raddbg_views.c line 5545
9. [0x7ff6b18cea6a] rd_window_frame +225162, raddbg_core.c line 7362
10. [0x7ff6b1882ba0] rd_frame +142336, raddbg_core.c line 16557
11. [0x7ff6b181707b] entry_point +29867, raddbg_main.c line 982
12. [0x7ff6b180f8f5] main_thread_base_entry_point +19269, base_entry_point.c line 92
13. [0x7ff6b17b7003] wWinMain +2691, os_core_win32.c line 1737
14. [0x7ff6b1972cee] __scrt_common_main_seh +262, exe_common.inl line 288
15. [0x7ffe6df07344] KERNEL32
16. [0x7ffe6f2c26b1] ntdll

Version: 0.9.14 [274b7103]

[Close]

**Comment by ryanfleury** [comment]
Fixed this crash in aa42d12d0fe58409d52cbc950cb5e44f3a668e29, although this uncovered another bug for me, which would be providing incorrect results for `[rdx+0x40]`. For now, I would just take the slow path and manually cast/dereference the address you're interested in. I'll fix this other bug as soon as possible too.
