### ISSUE TITLE
Issue with loading files on relaunsh of raddebugger.

### ISSUE THREAD

**Issue by JakWolf** [EpicGamesExt/raddebugger#379]
Everytime i reopen raddebugger i get a message that all the files i opened last session could not be loaded.
The directory is always wrong when that happens, for example:

Could not find "C://Users/Project/code" should load the file from "C://Users/Paul/Project/code" but is missing Paul somehow.

**Comment by ryanfleury** [comment]
To help me diagnose this, can you open the File Path Map tab and show a screenshot of what it contains? Thanks.

**Comment by JakWolf** [comment]
It's empty. I haven't added anything manually.

**Comment by JakWolf** [comment]
I upgraded the debugger to the newest version and i don't encounter the problem anymore. Should have done that sooner.

**Comment by ryanfleury** [comment]
Got it. Yeah, now that you mention that, this sounded like a familiar bug - should've asked for version & remembered it was fixed...
