### ISSUE TITLE
Panels are invisible after minimize

### ISSUE THREAD

**Issue by leidegre** [EpicGamesExt/raddebugger#385]
I just noticed that after having been minimized panels are no longer visible. This is with the latest code. I have to restart it to get it back, no amount of resizing or toggling of maximize/minimize seem to fix it.

https://github.com/user-attachments/assets/c0b30137-01f0-4b5b-b800-2b0c64331d3a

**Comment by ryanfleury** [comment]
Sorry about that. I still need to investigate why this started happening, but I've hacked in a fix that will prevent it in 4cb6e889efccc4d8b50f2302e7a2b6e9aa4c27e3.

**Comment by leidegre** [comment]
No worries, thanks for the quick turnaround!
