### ISSUE TITLE
[rust] Some values show up incorrectly

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EpicGamesExt/raddebugger#4]
I'm not sure how eager this project is in supporting Rust and I don't expect much at the moment, but since the Rust compiler outputs regular pdb's most of the features to work out of the box. However, in this particular case some values are displayed incorrectly.

![image](https://github.com/EpicGames/raddebugger/assets/49594/b0647a76-78fa-46f6-9a3f-65513ed8d4d9)

Visual Studio for reference
![image](https://github.com/EpicGames/raddebugger/assets/49594/56ad99e3-9fac-47fb-aa83-10768e1762a6)

My expectation would be that `fence_value` would be `1` (rust variables are immutable by default), and `self` would also contain a sensible value.

**Comment by Jasper-Bekkers** [comment]
Fwiw, I've tagged this as `rust` but don't think this would be a rust bug per-se, though it may be triggering some corner cases here and there.

**Comment by jestarray** [comment]
I've found rust has some issues with visual studio debugger as well. https://github.com/rust-lang/rust/issues/108972

**Comment by ryanfleury** [comment]
@Jasper-Bekkers Can you try this again with the newest location info fixes in 0.9.6? Thanks.

**Comment by ryanfleury** [comment]
Many relevant systems have been fixed & changed since this was posted, so this may have been resolved. I've not reproduced this exact Rust situation locally (as it seems easiest to identify in fairly contextual circumstances), so please re-open this issue if you notice the same bugs on newer builds.
