### ISSUE TITLE
Hovering over rsp in the disassembly view doesn't show the value

### ISSUE THREAD

**Issue by emoon** [EpicGamesExt/raddebugger#41]
As stated in the title if you hover with the mouse cursor over `rsp` the value of it isn't shown.

**Comment by tonsa1** [comment]
![kuva](https://github.com/EpicGames/raddebugger/assets/13787455/ea4a9d5c-cad5-495a-a757-eb3a27772d85)
It works normally for me when I'm hovering over `rsp` when its not used as memory address. Are you trying to hover when its inside square brackets?

**Comment by emoon** [comment]
Inside brackets yes

**Comment by ryanfleury** [comment]
This has to do with the "hover-eval parsing" rules, which are heuristic and subtly language-dependent. Still a lot of work to do with "assembly-awareness" both in the evaluation expression language and in the disassembly view, but I've been working on some lower level systems for disassembly recently and have fixed this case as of 5aa8aa1c6661eca1649369d104c4a3d6839f4d1f. This will be in the next release.
