### ISSUE TITLE
Double clicking on words inside the disassembly view doesn't work

### ISSUE THREAD

**Issue by emoon** [EpicGamesExt/raddebugger#45]
Double clicking on words (such as the address location) is useful when needing to copy them to to put them into another view (such as memory) Drag selection works nice, but double clicking just make this faster.

**Comment by ryanfleury** [comment]
Done as of 8c5c0be0408f4d3d601ec7548594d6ac392b61ea. This change is on the `dev` branch currently but will be in `master` shortly, and the next release.
