### ISSUE TITLE
Bitfield support

### ISSUE THREAD

**Issue by Vincent-P** [EpicGamesExt/raddebugger#54]
A simple struct with bitfields is not visible in either the Watch or Locals window.

```c
struct Pointer
{
	uint32_t type : 2;
	uint32_t offset : 30;
};
```
![image](https://github.com/EpicGames/raddebugger/assets/10779205/6cb4447b-7269-47c2-8a32-03d5d7510f72)

**Comment by ryanfleury** [comment]
Support added as of 60030b298b822a9b27238e80ab98f479a0b43f33. This is in `dev` right now, but will be in `master` and the next release shortly.

![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/5d5940a0-bb05-4445-9659-731bffae97be)
