### ISSUE TITLE
File search issues.

### ISSUE THREAD

**Issue by DevAgu93** [EpicGamesExt/raddebugger#70]
1. If you previously left the directory bar empty and press ctrl+o to look for files, it doesn't display any files, then if you press "up one directory" a "/"appears and you have to manually delete it so it detects the main drive.
2. If you select a file like this, it doesn't take the full path correctly when selecting it (in the example, it uses "dev\orbe\file.c" instead of "c:\dev\orbe\file.c" in the video you can see that I had to manually put "c:"

https://github.com/EpicGames/raddebugger/assets/63572671/db56e2d8-5e28-46fe-ab15-cc436adade9f

Also a minor annoyance, but when you type the file name, it doesn't count the directories so they all disappear.

**Comment by ryanfleury** [comment]
Fixed in 59e71eb5ccf41b32ef8d4d59818fcbf5e412a9a5.
