### ISSUE TITLE
Select a word/line by clicking/double-clicking on the text

### ISSUE THREAD

**Issue by 1ndahous3** [EpicGamesExt/raddebugger#81]
Useful feature in most text viewers, editors, IDEs, etc.

Comparison of Visual Studio/Sublime Text/RAD Debugger:
![text_click_select](https://github.com/EpicGames/raddebugger/assets/9205230/1724d00b-2d67-4e8f-83a8-164807c04e1c)

**Comment by 1ndahous3** [comment]
Similar to https://github.com/EpicGames/raddebugger/issues/45, but in text.

**Comment by mmozeiko** [comment]
On TODO list here: https://github.com/EpicGames/raddebugger/blob/d172b3a059af35937b9cd7be5d73ceb35084c591/src/raddbg/raddbg.h#L182

**Comment by ryanfleury** [comment]
Done as of 8c5c0be0408f4d3d601ec7548594d6ac392b61ea. This change is on the `dev` branch currently but will be in `master` shortly, and the next release.
